# Generated by Django 5.1.1 on 2025-04-28 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.AlterField(
            model_name='document',
            name='auteur',
            field=models.CharField(blank=True, default='Inconnu', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='genre',
            field=models.CharField(blank=True, default='Inconnu', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('livre', 'Livre imprimé'), ('cd', 'CD / Audio'), ('dvd', 'DVD / Blu-Ray'), ('magazine', 'Magazine / Périodique')], max_length=20),
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_reelle', models.DateField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.document')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
