# Generated by Django 5.1.1 on 2025-04-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_profilutilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='duree_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nombre_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='auteur',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('livre', 'Livre imprimé'), ('cd', 'CD / Audio'), ('dvd', 'DVD / Blu-Ray'), ('magazine', 'Magazine / Périodique')], max_length=10),
        ),
    ]
