# Generated by Django 5.1.1 on 2025-04-28 21:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_document_duree_minutes_document_nombre_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='date_abonnement',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='lettre_envoyee',
            field=models.BooleanField(default=False),
        ),
    ]
