# Generated by Django 5.1.1 on 2025-04-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_profilutilisateur_date_abonnement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_sortie',
            field=models.DateField(blank=True, null=True),
        ),
    ]
