# Generated by Django 5.1.1 on 2025-04-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_emprunt_date_emprunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='etudiant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
