# Generated by Django 5.1.1 on 2025-04-30 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_profilutilisateur_date_naissance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilutilisateur',
            old_name='etudiant',
            new_name='scolarise_agglomeration',
        ),
    ]
